---
version: '3'

env:
  KUBECONFIG: ./kubeconfig

tasks:
  secrets:create:
    desc: Create secrets
    cmds:
    - ./hack/create-secrets.sh
    preconditions:
    - test -f ./hack/create-secrets.sh
    - test -f .cluster-secrets.env

  secrets:apply:
    desc: Apply secrets to the Kubernetes cluster
    cmds:
    - kubectl apply -f ./cluster/zz_generated_secrets.yaml
    preconditions:
    - test -f ./cluster/zz_generated_secrets.yaml

  renovate:helm-releases:
    desc: Create renovate annotations for HelmReleases
    cmds:
    - ./hack/create-helmrelease-annotations.sh
    preconditions:
    - test -f ./hack/create-helmrelease-annotations.sh

  blocky:enable:
    desc: Enable adblocking in blocky
    cmds:
    - ./hack/blocky.sh enable
    preconditions:
    - test -f ./hack/blocky.sh

  blocky:disable:
    desc: Disable adblocking in blocky
    cmds:
    - ./hack/blocky.sh disable
    preconditions:
    - test -f ./hack/blocky.sh

  #
  # WIP
  #
  generate:helm-secret:
    desc: Create helm value file secrets
    cmds:
    - ./hack/create-helm-secret.sh {{.TXT_FILE}}
    preconditions:
    - test -f ./hack/create-helm-secret.sh
    - test -f .cluster-secrets.env
