---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClassReplicaCount: 3
      defaultClass: false
    csi:
      kubeletRootDir: /var/lib/kubelet
    defaultSettings:
      defaultReplicaCount: 3
      createDefaultDiskLabeledNodes: true
      backupTarget: s3://longhorn@minio/backups
      backupTargetCredentialSecret: aws-secret
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
  valuesFrom:
  - kind: Secret
    name: "longhorn-helm-values"
