---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.kasten.io
      chart: k10
      version: 3.0.7
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 6m
  values:
    eula:
      accept: true
      company: elCarpenter
      email: drewmich@elcarpenter.com
    global:
      persistence:
        storageClass: rook-ceph-block
    auth:
      basicAuth:
        enabled: true
        secretName: media/nginx-basic-auth
      k10AdminUsers:
      - drewmich@elcarpenter.com
      # oidcAuth:
      #   enabled: true
      #   providerURL: https://dex.holthome.net
      #   redirectURL: https://k10.holthome.net
      #   scopes: "profile email"
      #   usernameClaim: "email"
      #   clientID: k10
    clusterName: k8s
    ingress:
      create: true
      class: "nginx"
      host: k10.storage.elcarpenter.com
      annotations:
        kubernetes.io/ingress.class: "internal"
        # nginx.ingress.kubernetes.io/auth-url: "https://auth.elcarpenter.com/oauth2/auth"
        # nginx.ingress.kubernetes.io/auth-signin: "https://auth.elcarpenter.com/oauth2/start"
        # nginx.ingress.kubernetes.io/configuration-snippet: |
        # #   # Bypass auth for requests from local network
        # #   # This works, but are there some security concerns?
        # #   satisfy any;
        # #   allow 192.168.0.0/16;
        # #   allow 172.16.0.0/12;
        # #   allow 10.0.0.0/8;
        # #   deny all;
      hosts:
      - host: k10.storage.elcarpenter.com
        paths:
        - path: /
          pathType: Prefix
      tls:
        enabled: true
        secretName: cert-manager/letsencrypt-production
  #   resources:
  #     requests:
  #       memory: 250Mi
  #       cpu: 25m
  #     limits:
  #       memory: 250Mi
  # valuesFrom:
  # - kind: Secret
  #   name: "k10-helm-values"
  #   optional: false
