---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten
spec:
  releaseName: k10
  interval: 6m
  chart:
    spec:
      # renovate: registryUrl=https://charts.kasten.io/
      chart: k10
      version: 3.0.7
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  values:
    eula:
      accept: true
      company: elCarpenter
      email: drewmich@elcarpenter.com
    global:
      persistence:
        storageClass: rook-ceph-block
    clusterName: k8s
    ingress:
      create: true
      class: "nginx"
      host: k10.storage.elcarpenter.com
      urlPath: /
      annotations:
        kubernetes.io/ingress.class: "external"
      hosts:
      - host: k10.storage.elcarpenter.com
        paths:
        - path: /
          pathType: Prefix
      tls:
        enabled: true
        secretName: "kube-system/elcarpenter-com-tls"
  #   resources:
  #     requests:
  #       memory: 250Mi
  #       cpu: 25m
  #     limits:
  #       memory: 250Mi
        claimName: nfs-nas-media-pvc
  valuesFrom:
  - kind: Secret
    name: "k10-helm-values"
    optional: false
