---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hyperion-ng
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 7.7.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: hyperion-ng
    controllerType: deployment
    image:
      repository: sirfragalot/hyperion.ng
      tag: 2.0.0-alpha.8-x86_64
      pullPolicy: Always
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "100"
    service:
      type: LoadBalancer
      externalIPs:
      - 10.201.40.70
      port:
        port: 8090
      # additionalServices:
      # - enabled: true
      #   nameSuffix: protobufservice
      #   type: LoadBalancer
      #   externalIPs:
      #   - 10.201.40.70
      #   port:
      #     port: 19445
      #     name: protobufservice
      #     protocol: TCP
      #     targetPort: 19445
      #   externalTrafficPolicy: Local
      additionalPorts:
      - port: 19444
        name: jsonservice
        protocol: TCP
        targetPort: 19444
      - port: 19445
        name: protobufservice
        protocol: TCP
        targetPort: 19445
      - port: 19333
        name: boblightservice
        protocol: TCP
        targetPort: 19333
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
        nginx.ingress.kubernetes.io/auth-url: "https://auth.elcarpenter.com/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.elcarpenter.com/oauth2/start"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          # Bypass auth for requests from local network
          # This works, but are there some security concerns?
          satisfy any;
          allow 192.168.0.0/16;
          allow 172.16.0.0/12;
          allow 10.0.0.0/8;
          deny all;
      hosts:
      - host: hyperion.home.elcarpenter.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "hyperion.home.elcarpenter.com"
    persistence:
      config:
        enabled: true
        existingClaim: config-hyperion-ng

    # additionalVolumeMounts:
    # - name: media-serenity
    #   mountPath: "/media-serenity"
    # additionalVolumes:
    # - name: media-serenity
    #   persistentVolumeClaim:
    #     claimName: nfs-media-serenity-pvc

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node04
              # - k8s-worker-e

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
