---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-unifi
  namespace: network
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 20Gi
