---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-plex-auto-collections
  namespace: media
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
