---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nas-media-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media
  # volumeName: nfs-nas-media-pv
  resources:
    requests:
      storage: 1Mi
