---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-radarr
  namespace: media
spec:
  storageClassName: openebs-cstor-sparse
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
