---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-nzbget-test
spec:
  storageClassName: openebs-cstor-sparse
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi