---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-nzbget
  namespace: media
spec:
  storageClassName: openebs-cstor-sparse
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
