---
#
# Cronjob to back up my longhorn backups to the cloud
# Thanks @onedr0p!
#
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: velero
  name: rclone-sync-velero
  annotations:
    fluxcd.io/ignored: "false"
    fluxcd.io/automated: "false"
spec:
  suspend: false
  # Run once a day, every day, starting at 3AM
  schedule: "0 3 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          dnsConfig:
            nameservers:
            - 10.201.50.10
          initContainers:
          - name: rclone-conf
            image: alpine/git:v2.30.0
            env:
            - name: GITEA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea-pat
                  key: token
            command:
            - "/bin/sh"
            - "-ec"
            - |
              set -o nounset
              set -o errexit
              if [ -z "${GITEA_TOKEN}" ]; then
                printf "%s - Error - Missing GITEA_TOKEN environment variable" "$(date -u)"
                exit 1
              fi
              git clone --depth 1 "https://${GITEA_TOKEN}@git.dev.elcarpenter.com/dcplaya/RClone.git" /shared
              exit 0
            volumeMounts:
            - name: shared
              mountPath: /shared
          containers:
          - name: rclone
            image: rclone/rclone:1.54
            imagePullPolicy: IfNotPresent
            env:
            - name: TZ
              value: "America/Los_Angeles"
            command: ["rclone"]
            args:
            - "-vvv"
            - "--config"
            - "/shared/RClone/Configs/default.conf"
            - "sync"
            - "--ignore-errors"
            - "--fast-list"
            - "--b2-hard-delete"
            - "--transfers"
            - "24"
            - "--checkers"
            - "24"
            - "--bwlimit"
            - "50M"
            - "minio:velero"
            - "backblaze-velero-crypt:/"
            resources:
              requests:
                memory: 1000Mi
                cpu: 1500m
              limits:
                cpu: 2500m
                # memory: 2000Mi
            volumeMounts:
            - mountPath: /shared
              name: shared
          volumes:
          # Location of rclone.conf
          - name: shared
            emptyDir: {}
