---
#
# Cronjob to back up my longhorn backups to the cloud
# Thanks @onedr0p!
#
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: velero
  name: rclone-sync-velero
  annotations:
    fluxcd.io/ignored: "false"
    fluxcd.io/automated: "false"
spec:
  suspend: false
  # Run once a day, every day, starting at 3AM
  schedule: "0 3 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rclone
            image: rclone/rclone:1.54
            imagePullPolicy: IfNotPresent
            env:
            - name: TZ
              value: "America/Los_Angeles"
            command:
            # - /bin/sh
            # - "-c"
            # - "apk update && apk add openssh && apk add rsync && sleep 600000000m"
            - "rclone"
            - "-vvv"
            - "--config"
            - "/config/rclone.conf"
            - "sync"
            - "--ignore-errors"
            - "--fast-list"
            - "--b2-hard-delete"
            - "--retries 1"
            # - "--transfers"
            # - "24"
            # - "--checkers"
            # - "24"
            # - "--bwlimit"
            # - "50M"
            - "minio:velero"
            - "backblaze-velero-crypt:/"
            volumeMounts:
            - mountPath: /config
              name: rclone-sync-backup
              subPath: rclone
              readOnly: false
          restartPolicy: Never
          volumes:
          # Location of rclone.conf
          - name: rclone-sync-backup
            persistentVolumeClaim:
              claimName: nfs-config-pvc
