---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://coredns.github.io/helm
      chart: coredns
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    rbac:
      create: true
    replicaCount: 3
    isClusterService: false
    serviceType: LoadBalancer
    service:
      externalIPs:
      - 10.201.50.10
      externalTrafficPolicy: Local
    servers:
    - zones:
      - zone: media.elcarpenter.com. unifi.elcarpenter.com. home.elcarpenter.com. network.elcarpenter.com. auth.elcarpenter.com. backup.elcarpenter.com. dashboards.elcarpenter.com. devops.elcarpenter.com. monitoring.elcarpenter.com. storage.elcarpenter.com. dev.elcarpenter.com.
        scheme: dns://
        # use_tcp: true
      port: 53
      plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
      - name: prometheus
        parameters: 0.0.0.0:9153
      # - name: forward
      #   parameters: iot.elcarpenter.com 10.10.200.1
      # - name: forward
      #   parameters: lan.elcarpenter.com 10.10.200.1
      # - name: forward
      #   parameters: jeff.elcarpenter.com 10.10.16.1
      # - name: forward
      #   parameters: amber.elcarpenter.com 10.10.17.1
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
      - name: etcd
        parameters: media.elcarpenter.com unifi.elcarpenter.com home.elcarpenter.com network.elcarpenter.com auth.elcarpenter.com backup.elcarpenter.com dashboards.elcarpenter.com devops.elcarpenter.com monitoring.elcarpenter.com storage.elcarpenter.com dev.elcarpenter.com
        configBlock: |-
          stubzones
          path /skydns
          endpoint http://etcd:2379
    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
