---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdeployment
  namespace: actions-runner-system
  annotations:
    botkube.io/disable: "true"
spec:
  template:
    spec:
      repository: onedr0p/home-cluster
      image: k8sathome/actions-runner:latest
      imagePullPolicy: Always
      env: []
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runnerdeployment-autoscaler
  namespace: actions-runner-system
  annotations:
    botkube.io/disable: "true"
spec:
  scaleTargetRef:
    name: runnerdeployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - onedr0p/home-cluster
