---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdeployment
  namespace: actions-runner-system
  annotations:
    botkube.io/disable: "true"
spec:
  template:
    spec:
      repository: dcplaya/home-cluster
      image: ghcr.io/k8s-at-home/actions-runner:v2.276.1
      imagePullPolicy: Always
      env: []
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runnerdeployment-autoscaler
  namespace: actions-runner-system
  annotations:
    botkube.io/disable: "true"
spec:
  scaleTargetRef:
    name: runnerdeployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - dcplaya/home-cluster
