---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: media
  name: cloudplow-uploader
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
  labels:
    app: cloudplow-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudplow-uploader
  template:
    metadata:
      labels:
        app: cloudplow-uploader
    spec:
      containers:
        - name: cloudplow-uploader
          image: sabrsorensen/alpine-cloudplow:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: GUID
              value: "1000"
            - name: CLOUDPLOW_CONFIG
              value: "/volume1/Media/config/cloudplow/config.json"
            - name: CLOUDPLOW_LOGFILE
              value: "/volume1/Media/config/cloudplow/cloudplow.log"
            - name: CLOUDPLOW_LOGLEVEL
              value: "INFO"
            - name: CLOUDPLOW_CACHEFILE
              value: "/volume1/Media/config/cloudplow/cache.db"
            - name: TZ
              value: "America/Los_Angeles"
          volumeMounts:
            - mountPath: /volume1/Media
              name: media-pvc
          resources:
            requests:
              memory: 500Mi
              cpu: 1000m
            limits:
              memory: 2000Mi
              cpu: 1000m
      volumes:
        - name: media-pvc
          persistentVolumeClaim:
            claimName: nfs-nas-media-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                  - node00
                  - node04
