---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-plex
  namespace: home
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
