---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-hyperion-ng
  namespace: home
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
