---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-home-assistant-influxdb
  namespace: home
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
