---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-esphome
  namespace: home
spec:
  storageClassName: openebs-cstor-sparse
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
