---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nas-config-pv
  annotations:
    fluxcd.io/ignore: "false"
spec:
  storageClassName: config
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.200.210
    path: /volume1/Media/config
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=32768
    - wsize=32768
