---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-config
  namespace: velero
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: config
  resources:
    requests:
      storage: 1Mi
