---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-config-pvc
  namespace: velero
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
