---
apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: radarr
  namespace: kasten
spec:
  comment: ""
  frequency: "@daily"
  actions:
    - action: backup
      backupParameters:
        filters:
          includeResources:
            - group: ""
              version: ""
              resource: persistentvolumeclaims
              name: config-radarr
              label: []
            - group: ""
              version: ""
              resource: persistentvolumeclaims
              name: config-sonarr
              label: []
            - group: ""
              version: ""
              resource: persistentvolumeclaims
              name: config-tautulli
              label: []
          excludeResources:
            - group: ""
              version: ""
              resource: persistentvolumeclaims
              name: nfs-nas-media-pvc
              label: []
            - group: ""
              version: ""
              resource: persistentvolumeclaims
              name: nfs-nas-merged-media-pvc
              label: []
        profile:
          namespace: kasten
          name: minio
    - action: export
      exportParameters:
        frequency: "@daily"
        migrationToken:
          name: ""
          namespace: ""
        profile:
          name: minio
          namespace: kasten
        receiveString: ""
        exportData:
          enabled: true
          overrides:
            - storageClassName: nfs
              enabled: false
      retention:
        hourly: 0
        daily: 0
        weekly: 0
        monthly: 0
        yearly: 0
  retention:
    hourly: 1
    daily: 1
    weekly: 1
    monthly: 1
    yearly: 1
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - default
