---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://helm.min.io/
      chart: minio
      version: 8.0.9
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    image:
      repository: minio/minio
      tag: RELEASE.2020-09-17T04-49-20Z
      pullPolicy: Always
    mcImage:
      repository: minio/mc
      tag: RELEASE.2020-08-08T02-33-58Z
      pullPolicy: Always
    helmKubectlJqImage:
      repository: bskim45/helm-kubectl-jq
      tag: 3.3.0
    securityContext:
      enabled: true
      runAsUser: 1000
      runAsGroup: 100
    persistence:
      existingClaim: "nfs-backup-pvc"
      storageClass: "backup"
      subPath: "minio"

    metrics:
      serviceMonitor:
        enabled: true

    nasgateway:
      enabled: true
      # Number of parallel instances
      replicas: 3

    service:
      type: LoadBalancer
      externalIPs:
      - 10.201.10.55
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"

    readinessProbe:
      initialDelaySeconds: 10

    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node00
              - node04

  valuesFrom:
  - kind: Secret
    name: "minio-helm-values"
