---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: adguard/adguardhome
      tag: edge
      pullPolicy: Always
    persistence:
      config:
        enabled: false
      work:
        enabled: true
        existingClaim: database-adguard-home
    timezone: "America/Los_Angeles"
    ## Currently not working
    # tlsSecretName: "kube-system/elcarpenter-com-tls"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - dns01.network.elcarpenter.com
      tls:
      - hosts:
        - dns01.network.elcarpenter.com
    # service:
    #   type: LoadBalancer
    #   externalIPs:
    #   - 10.201.50.11
    serviceTCP:
      enabled: true
      type: LoadBalancer
      externalIPs:
      - 10.201.50.11
    serviceUDP:
      enabled: true
      type: LoadBalancer
      externalIPs:
      - 10.201.50.11
    serviceDNSOverTLS:
      enabled: true
      type: LoadBalancer
      externalIPs:
      - 10.201.50.11
    resources:
      requests:
        memory: 2000Mi
        cpu: 200m
      limits:
        memory: 1000Mi
  # Include config as a RO configMap
  valuesFrom:
  - kind: Secret
    name: "adguard-home-dns01-config-helm-values"
