---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: adguard/adguardhome
      tag: edge
      pullPolicy: Always
    persistence:
      config:
        enabled: false
      work:
        enabled: true
        existingClaim: database-adguard-home
    timezone: "America/Los_Angeles"

    ## Currently not working
    # tlsSecretName: "kube-system/elcarpenter-com-tls"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/auth-url: "https://auth.elcarpenter.com/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.elcarpenter.com/oauth2/start"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          # Bypass auth for requests from local network
          # This works, but are there some security concerns?
          satisfy any;
          allow 192.168.0.0/16;
          allow 172.16.0.0/12;
          allow 10.0.0.0/8;
          deny all;
      hosts:
      - dns01.network.elcarpenter.com
      tls:
      - hosts:
        - dns01.network.elcarpenter.com

    service:
      type: LoadBalancer
      externalIPs:
      - 10.201.50.20
    serviceTCP:
      enabled: true
    serviceUDP:
      enabled: true
    serviceDNSOverTLS:
      enabled: true

    resources:
      requests:
        memory: 500Mi
        cpu: 20m
      limits:
        memory: 750Mi

  # Include config as a RO configMap
  valuesFrom:
  - kind: Secret
    name: "adguard-home-dns01-config-helm-values"
