---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autoscan
  namespace: media
  labels:
    service: autoscan
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 8.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: autoscan
    controllerType: deployment
    image:
      repository: cloudb0x/autoscan
      tag: latest
      pullPolicy: Always
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "100"
    service:
      port:
        port: 3030
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: "external"
        # nginx.ingress.kubernetes.io/auth-url: "https://auth.elcarpenter.com/oauth2/auth"
        # nginx.ingress.kubernetes.io/auth-signin: "https://auth.elcarpenter.com/oauth2/start"
        # nginx.ingress.kubernetes.io/configuration-snippet: |
        #   # Bypass auth for requests from local network
        #   # This works, but are there some security concerns?
        #   satisfy any;
        #   allow 192.168.0.0/16;
        #   allow 172.16.0.0/12;
        #   allow 10.0.0.0/8;
        #   deny all;
      hosts:
      - host: autoscan.media.elcarpenter.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "autoscan.media.elcarpenter.com"
    persistence:
      config:
        enabled: true
        existingClaim: config-autoscan
    podAnnotations:
      backup.velero.io/backup-volumes: config
    additionalVolumeMounts:
    - name: nfs-nas-merged-media-pvc
      mountPath: "/mnt/unionfs"
    additionalVolumes:
    - name: nfs-nas-merged-media-pvc
      persistentVolumeClaim:
        claimName: nfs-nas-merged-media-pvc
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node04
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
