---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dizquetv
  namespace: media
  labels:
    service: dizquetv
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: dizquetv
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    # fullnameOverride: dizquetv
    controllerType: deployment
    image:
      repository: vexorian/dizquetv
      tag: edge
      pullPolicy: Always
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "100"
    # service:
      # port:
        # port: 8000
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: plex-tv.media.elcarpenter.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "plex-tv.media.elcarpenter.com"
    persistence:
      config:
        enabled: true
        # mountPath: /home/node/app/.dizquetv
        existingClaim: config-dizquetv
    podAnnotations:
      backup.velero.io/backup-volumes: config
    probes:
      liveness:
        enabled: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node04
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
