---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jackett
      version: 5.7.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: k8sathome/jackett
      tag: v0.16.2269
      pullPolicy: Always
    env:
      TZ: "America/Lost_Angeles"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: jackett.media.elcarpenter.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "jackett.media.elcarpenter.com"
    persistence:
      config:
        enabled: true
        existingClaim: config-jackett
        # storageClass: "longhorn"
        # accessMode: ReadWriteOnce
        # size: "1Gi"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
