---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: media
spec:
  containers:
  - image: alpine:3.2
    command:
      - /bin/sh
      - "-c"
      - "sleep 600000000m"
    imagePullPolicy: IfNotPresent
    name: alpine
    volumeMounts:
    - mountPath: "/config"
      name: config-pvc
  restartPolicy: Always
  volumes:
    - name: config-pvc
      persistentVolumeClaim:
       claimName: config-plex
