---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: linuxserver/sonarr
      tag: preview
      pullPolicy: Always
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "100"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
        nginx.ingress.kubernetes.io/auth-url: "https://auth.elcarpenter.com/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.elcarpenter.com/oauth2/start"
        nginx.ingress.kubernetes.io/configuration-snippet: |
        #   # Bypass auth for requests from local network
        #   # This works, but are there some security concerns?
        #   satisfy any;
        #   allow 192.168.0.0/16;
        #   allow 172.16.0.0/12;
        #   allow 10.0.0.0/8;
        #   deny all;
      hosts:
      - host: tv.media.elcarpenter.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "tv.media.elcarpenter.com"
      additionalIngresses:
      - enabled: true
        nameSuffix: "api"
        annotations:
          kubernetes.io/ingress.class: "external"
        hosts:
        - host: tv.media.elcarpenter.com
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - "tv.media.elcarpenter.com"
    persistence:
      config:
        enabled: true
        existingClaim: config-sonarr
    podAnnotations:
      backup.velero.io/backup-volumes: config
    additionalVolumeMounts:
    - name: nfs-nas-merged-media-pvc
      mountPath: "/mnt/unionfs"
    additionalVolumes:
    - name: nfs-nas-merged-media-pvc
      persistentVolumeClaim:
        claimName: nfs-nas-merged-media-pvc

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node04
              # - k8s-worker-e

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 3500Mi
