---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/dcplaya/home-cluster.git
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/cluster/
    /cluster/**/*.md
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  interval: 1m
  path: './cluster/'
  sourceRef:
    kind: GitRepository
    name: home-cluster
  prune: true