apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./gotk-components.yaml
- ./gotk-sync.yaml
- ./helm-chart-repositories/kubernetes-stable-charts.yaml
- ./helm-chart-repositories/k8s-at-home-charts.yaml
