---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  username: dcplaya
  channel: cluster
  secretRef:
    name: discord-webhook
