---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: external-drew-switch01
  annotations:
    kubernetes.io/ingress.class: "internal"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - host: switch01.network.elcarpenter.com
    http:
      paths:
      - backend:
          serviceName: external-drew-switch01
          servicePort: 80
  tls:
  - hosts:
    - switch01.network.elcarpenter.com
---
apiVersion: v1
kind: Service
metadata:
  name: external-drew-switch01
spec:
  ports:
  - name: http
    port: 80
  externalIPs:
  - 10.10.1.3
#  type: ExternalName
#  externalName: 10.10.1.3
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-drew-switch01
subsets:
- addresses:
  - ip: 10.10.1.3
  ports:
  - name: http
    port: 80
    protocol: TCP
