---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-blackbox-exporter
      version: 4.10.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - "blackbox.monitoring.elcarpenter.com"
      tls:
      - hosts:
        - "blackbox.monitoring.elcarpenter.com"
    allowIcmp: true
    config:
      modules:
        icmp:
          prober: icmp
          timeout: 30s
          icmp:
            preferred_ip_protocol: "ip4"
        http_2xx:
          prober: http
          timeout: 30s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2"]
            no_follow_redirects: false
            preferred_ip_protocol: "ip4"
    serviceMonitor:
      enabled: true
      defaults:
        labels:
          release: prometheus
        interval: 30s
        scrapeTimeout: 30s
      targets:
      - name: node00
        url: 10.10.200.50
        module: icmp
      - name: node01
        url: 10.10.200.51
        module: icmp
      - name: node02
        url: 10.10.200.52
        module: icmp
      - name: node03
        url: 10.10.200.53
        module: icmp
      - name: jode04
        url: 10.10.200.54
        module: icmp
    prometheusRule:
      enabled: true
      additionalLabels:
        app: prometheus-operator
        release: prometheus
      rules:
      - alert: HostDown
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          message: The host {{"{{ $labels.target }}"}} is currently unreachable
      - alert: SlowResponseTime
        annotations:
          message: The response time for {{"{{ $labels.target }}"}} has been greater than 30 seconds for 5 minutes.
        expr: probe_duration_seconds > 30
        for: 5m
        labels:
          severity: warning
