---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: flood
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: jesec/flood
      tag: 4.3.0
      pullPolicy: Always
    env:
      FLOOD_OPTION_RUNDIR: /data
      FLOOD_OPTION_AUTH: "none"
      FLOOD_OPTION_QBURL: "http://qb.media.svc.cluster.local:8080"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
      hosts:
      - host: flood.media.elcarpenter.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "flood.media.elcarpenter.com"
    persistence:
      data:
        enabled: true
        existingClaim: config-flood
        # storageClass: "longhorn"
        # accessMode: ReadWriteOnce
        # size: "1Gi"
    # podAnnotations:
    #   backup.velero.io/backup-volumes: data
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
  valuesFrom:
  - kind: Secret
    name: "flood-helm-values"
