---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 2.1.11
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  # dependsOn:
  # - name: sealed-secrets
  #   namespace: kube-system
  values:
    persistence:
      enabled: true
      existingClaim: config-gitea
    podAnnotations:
      backup.velero.io/backup-volumes: config,data
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/proxy-body-size: 128m
      hosts:
      - "git.dev.elcarpenter.com"
      tls:
      - hosts:
        - "git.dev.elcarpenter.com"
    service:
      http:
        port: 3000
      ssh:
        type: LoadBalancer
        port: 22
        externalTrafficPolicy: Local
        externalIPs:
        - 10.201.50.60
    gitea:
      admin:
        username: "dcplaya"
        email: "dcplaya@gmail.com"
      config:
        APP_NAME: "Home Gitea"
        server:
          ROOT_URL: https://git.dev.elcarpenter.com
          DISABLE_SSH: FALSE
          SSH_PORT: 22
          SSH_LISTEN_PORT: 22
        respository:
          DEFAULT_PRIVATE: true
        admin:
          DISABLE_REGULAR_ORG_CREATION: true
        security:
          PASSWORD_COMPLEXITY: "lower,upper"
          MIN_PASSWORD_LENGTH: 12
        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: true
      database:
        builtIn:
          postgresql:
            enabled: true
      cache:
        builtIn:
          enabled: true
    memcached:
      image:
        repository: bitnami/memcached
        tag: 1.6.9
      service:
        port: 11211
    postgresql:
      image:
        repository: bitnami/postgresql
        tag: 11.11.0
      persistence:
        storageClass: "rook-ceph-block"
      podAnnotations:
        backup.velero.io/backup-volumes: data
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node00
              - node04
  valuesFrom:
  - kind: Secret
    name: "gitea-helm-values"
