---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  # dependsOn:
  # - name: sealed-secrets
  #   namespace: kube-system
  values:
    image:
      repository: homeassistant/home-assistant
      tag: dev
      pullPolicy: Always
    extraEnv:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "100"

    hostNetwork: true
    service:
      type: LoadBalancer
      externalIPs:
      - 10.201.40.60
      externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
      hosts:
      - "home.elcarpenter.com"
      tls:
      - hosts:
        - "home.elcarpenter.com"

    persistence:
      enabled: true
      existingClaim: "config-home-assistant"
      # size: 10Gi
      # storageClass: "rook-ceph-block"
    # podAnnotations:
    #   backup.velero.io/backup-volumes: config
    monitoring:
      enabled: false

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
      limits:
        memory: 2500Mi

    # hostMounts:
    # - name: zha
    #   hostPath: "/dev/zigbee"

    affinity:
      # nodeAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #     - matchExpressions:
      #       - {key: "feature.node.kubernetes.io/custom-zigbee", operator: In, values: ["true"]}
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - plex
          topologyKey: "kubernetes.io/hostname"

    postgresql:
      enabled: true
      postgresqlDatabase: homeassistant
      persistence:
        enabled: true
        storageClass: "rook-ceph-block"

    influxdb:
      enabled: true
      architecture: standalone
      database: home_assistant
      authEnabled: false
      updateStrategy: Recreate
      persistence:
        enabled: true
        storageClass: "rook-ceph-block"
        size: 30Gi

    vscode:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 3.8.0
      extraEnv:
        HASS_SERVER: "http://localhost:8123"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "internal"
        hosts:
        - "vscode.home.elcarpenter.com"
        tls:
        - hosts:
          - "vscode.home.elcarpenter.com"
  valuesFrom:
  - kind: Secret
    name: "home-assistant-helm-values"
