name: renovate

on:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  helm-releases:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 1

    - name: Create HelmRelease annotations
      run: ./hack/create-helmrelease-annotations.sh

    - name: Create pull request for HelmRelease annotations
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: helm-release-annotations
        title: "[renovate] create helmrelease annotations [ci-skip]"
        signoff: true
        committer: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
        author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
        commit-message: Create renovatebot helmrelease annotations
        body: |
          Signed-off-by: DCPlaya <dcplaya@users.noreply.github.com>
        labels: renovate/helm-release-annotations
