name: renovate-helmrelease-schedule

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */6 * * *"

jobs:
  renovate-helmrelease:
    # runs-on: ubuntu-latest
    runs-on:
    - self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Run Kubernetes tools
      uses: stefanprodan/kube-tools@v1

    - name: Install yq
      run: |
        sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq

    - name: Create HelmRelease annotations
      run: ./hack/create-helmrelease-annotations.sh

    - name: Create pull request for HelmRelease annotations
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: helm-release-annotations
        delete-branch: true
        title: "Update HelmRelease annotations for Renovate [ci-skip]"
        signoff: true
        committer: "Drew Carpenter <dcplaya@users.noreply.github.com>"
        author: "Drew Carpenter <dcplaya@users.noreply.github.com>"
        assignees: "dcplaya"
        commit-message: "Update HelmRelease annotations for Renovate [ci-skip]"
        body: |
          Add comment annotations to HelmReleases inorder for Renovate to pick up new versions of Helm charts
        labels: renovate/helm-release-annotations