name: secrets

on:
  push:
    branches:
    - main
    paths:
    - "**.txt"
    - "**.env"
    - "!.cluster-secrets.sample.env"

env:
  DEBIAN_FRONTEND: "noninteractive"
  KUBECONFIG: "./kubeconfig"

jobs:
  sealed-secrets:
    runs-on:
    - self-hosted
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 1

    - name:  Update apt-get
      run: sudo apt-get update -y
      
    - name: Install git-crypt
      run: sudo apt-get install -y git-crypt

    - name: Unlock secrets
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      run: |
        echo "$GIT_CRYPT_KEY" | base64 -d > ./git-crypt-key
        git-crypt unlock ./git-crypt-key
        rm ./git-crypt-key

    - name: Create secrets
      run: |
        task secrets:create

    - name: Commit and push secrets
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          git config --global user.name "Drew Carpenter"
          git config --global user.email "DCPlaya@users.noreply.github.com"
          git add cluster/zz_generated_secrets.yaml
          git commit -sm "Auto-update sealed-secrets [ci-skip]" || exit 0
          git push
        fi

    - name: Apply secrets
      run: |
        task secrets:apply
